
package org.wso2.carbon.webapp.mgt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-20T13:24:53.115+01:00
 * Generated source version: 2.7.8
 * 
 */
public final class WebappAdminPortType_WebappAdminHttpsSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://mgt.webapp.carbon.wso2.org", "WebappAdmin");

    private WebappAdminPortType_WebappAdminHttpsSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebappAdmin.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebappAdmin ss = new WebappAdmin(wsdlURL, SERVICE_NAME);
        WebappAdminPortType port = ss.getWebappAdminHttpsSoap11Endpoint();  
        
        {
        System.out.println("Invoking expireAllSessions...");
        java.lang.String _expireAllSessions_webappFileName = "";
        port.expireAllSessions(_expireAllSessions_webappFileName);


        }
        {
        System.out.println("Invoking isDefaultVersionManagementEnabled...");
        java.lang.Boolean _isDefaultVersionManagementEnabled__return = port.isDefaultVersionManagementEnabled();
        System.out.println("isDefaultVersionManagementEnabled.result=" + _isDefaultVersionManagementEnabled__return);


        }
        {
        System.out.println("Invoking deleteAllStartedWebapps...");
        port.deleteAllStartedWebapps();


        }
        {
        System.out.println("Invoking uploadWebapp...");
        java.util.List<org.wso2.carbon.webapp.mgt.xsd.WebappUploadData> _uploadWebapp_webappUploadDataList = null;
        java.lang.Boolean _uploadWebapp__return = port.uploadWebapp(_uploadWebapp_webappUploadDataList);
        System.out.println("uploadWebapp.result=" + _uploadWebapp__return);


        }
        {
        System.out.println("Invoking changeDefaultAppVersion...");
        java.lang.String _changeDefaultAppVersion_appGroupName = "";
        java.lang.String _changeDefaultAppVersion_fileName = "";
        try {
            port.changeDefaultAppVersion(_changeDefaultAppVersion_appGroupName, _changeDefaultAppVersion_fileName);

        } catch (WebappAdminArtifactMetadataException e) { 
            System.out.println("Expected exception: WebappAdminArtifactMetadataException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPagedFaultyWebappsSummary...");
        java.lang.String _getPagedFaultyWebappsSummary_webappSearchString = "";
        java.lang.String _getPagedFaultyWebappsSummary_webappType = "";
        java.lang.Integer _getPagedFaultyWebappsSummary_pageNumber = null;
        org.wso2.carbon.webapp.mgt.xsd.WebappsWrapper _getPagedFaultyWebappsSummary__return = port.getPagedFaultyWebappsSummary(_getPagedFaultyWebappsSummary_webappSearchString, _getPagedFaultyWebappsSummary_webappType, _getPagedFaultyWebappsSummary_pageNumber);
        System.out.println("getPagedFaultyWebappsSummary.result=" + _getPagedFaultyWebappsSummary__return);


        }
        {
        System.out.println("Invoking isUnpackWARs...");
        java.lang.Boolean _isUnpackWARs__return = port.isUnpackWARs();
        System.out.println("isUnpackWARs.result=" + _isUnpackWARs__return);


        }
        {
        System.out.println("Invoking getActiveSessions...");
        java.lang.String _getActiveSessions_webappFileName = "";
        java.lang.Integer _getActiveSessions_pageNumber = null;
        org.wso2.carbon.webapp.mgt.xsd.SessionsWrapper _getActiveSessions__return = port.getActiveSessions(_getActiveSessions_webappFileName, _getActiveSessions_pageNumber);
        System.out.println("getActiveSessions.result=" + _getActiveSessions__return);


        }
        {
        System.out.println("Invoking deleteAllStoppedWebapps...");
        port.deleteAllStoppedWebapps();


        }
        {
        System.out.println("Invoking reloadWebapps...");
        java.util.List<java.lang.String> _reloadWebapps_webappFileNames = null;
        port.reloadWebapps(_reloadWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking deleteStoppedWebapps...");
        java.util.List<java.lang.String> _deleteStoppedWebapps_webappFileNames = null;
        port.deleteStoppedWebapps(_deleteStoppedWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking expireSessions...");
        java.lang.String _expireSessions_webappFileName = "";
        java.util.List<java.lang.String> _expireSessions_sessionIDs = null;
        port.expireSessions(_expireSessions_webappFileName, _expireSessions_sessionIDs);


        }
        {
        System.out.println("Invoking stopAllWebapps...");
        port.stopAllWebapps();


        }
        {
        System.out.println("Invoking stopWebapps...");
        java.util.List<java.lang.String> _stopWebapps_webappFileNames = null;
        port.stopWebapps(_stopWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking setBamConfiguration...");
        java.lang.String _setBamConfiguration_webappFileName = "";
        java.lang.String _setBamConfiguration_value = "";
        port.setBamConfiguration(_setBamConfiguration_webappFileName, _setBamConfiguration_value);


        }
        {
        System.out.println("Invoking getStartedWebapp...");
        java.lang.String _getStartedWebapp_webappFileName = "";
        org.wso2.carbon.webapp.mgt.xsd.WebappMetadata _getStartedWebapp__return = port.getStartedWebapp(_getStartedWebapp_webappFileName);
        System.out.println("getStartedWebapp.result=" + _getStartedWebapp__return);


        }
        {
        System.out.println("Invoking deleteStartedWebapps...");
        java.util.List<java.lang.String> _deleteStartedWebapps_webappFileNames = null;
        port.deleteStartedWebapps(_deleteStartedWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking deleteAllWebApps...");
        java.util.List<java.lang.String> _deleteAllWebApps_webappFileNames = null;
        port.deleteAllWebApps(_deleteAllWebApps_webappFileNames);


        }
        {
        System.out.println("Invoking deleteFaultyWebapps...");
        java.util.List<java.lang.String> _deleteFaultyWebapps_webappFileNames = null;
        port.deleteFaultyWebapps(_deleteFaultyWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking startWebapps...");
        java.util.List<java.lang.String> _startWebapps_webappFileNames = null;
        port.startWebapps(_startWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking deleteAllFaultyWebapps...");
        port.deleteAllFaultyWebapps();


        }
        {
        System.out.println("Invoking expireSessionsInAllWebapps...");
        port.expireSessionsInAllWebapps();


        }
        {
        System.out.println("Invoking getBamConfiguration...");
        java.lang.String _getBamConfiguration_webappFileName = "";
        java.lang.String _getBamConfiguration__return = port.getBamConfiguration(_getBamConfiguration_webappFileName);
        System.out.println("getBamConfiguration.result=" + _getBamConfiguration__return);


        }
        {
        System.out.println("Invoking getStoppedWebapp...");
        java.lang.String _getStoppedWebapp_webappFileName = "";
        org.wso2.carbon.webapp.mgt.xsd.WebappMetadata _getStoppedWebapp__return = port.getStoppedWebapp(_getStoppedWebapp_webappFileName);
        System.out.println("getStoppedWebapp.result=" + _getStoppedWebapp__return);


        }
        {
        System.out.println("Invoking expireSessionsInWebapps...");
        java.util.List<java.lang.String> _expireSessionsInWebapps_webappFileNames = null;
        port.expireSessionsInWebapps(_expireSessionsInWebapps_webappFileNames);


        }
        {
        System.out.println("Invoking startAllWebapps...");
        port.startAllWebapps();


        }
        {
        System.out.println("Invoking expireSessionsInWebapp...");
        java.lang.String _expireSessionsInWebapp_webappFileName = "";
        java.lang.Long _expireSessionsInWebapp_maxSessionLifetimeMillis = null;
        port.expireSessionsInWebapp(_expireSessionsInWebapp_webappFileName, _expireSessionsInWebapp_maxSessionLifetimeMillis);


        }
        {
        System.out.println("Invoking deleteWebapp...");
        java.lang.String _deleteWebapp_webappFileName = "";
        port.deleteWebapp(_deleteWebapp_webappFileName);


        }
        {
        System.out.println("Invoking reloadAllWebapps...");
        port.reloadAllWebapps();


        }
        {
        System.out.println("Invoking getPagedWebappsSummary...");
        java.lang.String _getPagedWebappsSummary_webappSearchString = "";
        java.lang.String _getPagedWebappsSummary_webappState = "";
        java.lang.String _getPagedWebappsSummary_webappType = "";
        java.lang.Integer _getPagedWebappsSummary_pageNumber = null;
        org.wso2.carbon.webapp.mgt.xsd.WebappsWrapper _getPagedWebappsSummary__return = port.getPagedWebappsSummary(_getPagedWebappsSummary_webappSearchString, _getPagedWebappsSummary_webappState, _getPagedWebappsSummary_webappType, _getPagedWebappsSummary_pageNumber);
        System.out.println("getPagedWebappsSummary.result=" + _getPagedWebappsSummary__return);


        }
        {
        System.out.println("Invoking downloadWarFileHandler...");
        java.lang.String _downloadWarFileHandler_fileName = "";
        java.lang.String _downloadWarFileHandler_webappType = "";
        byte[] _downloadWarFileHandler__return = port.downloadWarFileHandler(_downloadWarFileHandler_fileName, _downloadWarFileHandler_webappType);
        System.out.println("downloadWarFileHandler.result=" + _downloadWarFileHandler__return);


        }

        System.exit(0);
    }

}
