
package org.wso2.carbon.webapp.mgt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-20T13:24:53.156+01:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "WebappAdminArtifactMetadataException", targetNamespace = "http://org.apache.axis2/xsd")
public class WebappAdminArtifactMetadataException extends Exception {
    
    private axis2.apache.org.xsd.WebappAdminArtifactMetadataException webappAdminArtifactMetadataException;

    public WebappAdminArtifactMetadataException() {
        super();
    }
    
    public WebappAdminArtifactMetadataException(String message) {
        super(message);
    }
    
    public WebappAdminArtifactMetadataException(String message, Throwable cause) {
        super(message, cause);
    }

    public WebappAdminArtifactMetadataException(String message, axis2.apache.org.xsd.WebappAdminArtifactMetadataException webappAdminArtifactMetadataException) {
        super(message);
        this.webappAdminArtifactMetadataException = webappAdminArtifactMetadataException;
    }

    public WebappAdminArtifactMetadataException(String message, axis2.apache.org.xsd.WebappAdminArtifactMetadataException webappAdminArtifactMetadataException, Throwable cause) {
        super(message, cause);
        this.webappAdminArtifactMetadataException = webappAdminArtifactMetadataException;
    }

    public axis2.apache.org.xsd.WebappAdminArtifactMetadataException getFaultInfo() {
        return this.webappAdminArtifactMetadataException;
    }
}
