
package org.wso2.carbon.aarservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T10:35:02.259+01:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "Exception", targetNamespace = "http://aarservices.carbon.wso2.org")
public class Exception_Exception extends java.lang.Exception {
    
    private org.wso2.carbon.aarservices.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, org.wso2.carbon.aarservices.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, org.wso2.carbon.aarservices.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.wso2.carbon.aarservices.Exception getFaultInfo() {
        return this.exception;
    }
}
