package org.wso2.carbon.aarservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T10:35:02.314+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://aarservices.carbon.wso2.org", name = "ServiceUploaderPortType")
@XmlSeeAlso({ObjectFactory.class, org.wso2.carbon.aarservices.xsd.ObjectFactory.class})
public interface ServiceUploaderPortType {

    @WebResult(name = "return", targetNamespace = "http://aarservices.carbon.wso2.org")
    @Action(input = "urn:uploadService", output = "urn:uploadServiceResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "urn:uploadServiceException")})
    @RequestWrapper(localName = "uploadService", targetNamespace = "http://aarservices.carbon.wso2.org", className = "org.wso2.carbon.aarservices.UploadService")
    @WebMethod(action = "urn:uploadService")
    @ResponseWrapper(localName = "uploadServiceResponse", targetNamespace = "http://aarservices.carbon.wso2.org", className = "org.wso2.carbon.aarservices.UploadServiceResponse")
    public java.lang.String uploadService(
        @WebParam(name = "serviceDataList", targetNamespace = "http://aarservices.carbon.wso2.org")
        java.util.List<org.wso2.carbon.aarservices.xsd.AARServiceData> serviceDataList
    ) throws Exception_Exception;
}
